### ISSUE TITLE
Sheet-1 Fine Tuning.

### ISSUE THREAD

**Issue by iamchiragsharma** [Ngrover24198/Curb_your_matplotlib#1]
Following needs to be improved (Minor Tweaks):
* We have to keep in mind why we are dealing with newbies here. So they might ask why we use
```import matplot.pyplot as plt```
    * We need to add more casual info to this like why we use pyplot specifically we have to mention the reason for these small codes.

* First Lineplot: only a single array was used but students might come to think about how we can draw a line with only one variable. Please shed some light on that too.

* Multiline plots: More explanation about what happens if we don't use ```plt.show()``` after all ```plt.plot()```. We need to explain more cases of unexpected behaviors everywhere.

* Also add how to control the figure size and other label/font size.

* __Please keep in mind as a general rule of thumb to be consistent we are not teaching we are telling a story and a good story needs to be engaging.__

**Comment by Ngrover24198** [comment]
Have updated the notebooks. Thanks
