### ISSUE TITLE
Sheet 3 Image Not Loading

### ISSUE THREAD

**Issue by iamchiragsharma** [Ngrover24198/Curb_your_matplotlib#2]
![Screenshot from 2020-05-18 13-14-41](https://user-images.githubusercontent.com/29746593/82187233-bba30580-9909-11ea-8060-08cf06a62925.png)
Here the Image is not loading. Fix this issue

**Comment by karanhans** [comment]
![error sheet2 matplotlib](https://user-images.githubusercontent.com/32808986/82452221-9d393780-9acc-11ea-9010-a169db6dfd1b.png)

We have same issue in sheet 4 also . Fix that too .

**Comment by Ngrover24198** [comment]
Issue resolved, thanks guys
